# Milestone 2
**Name:** Eula Fullerton  
**Due Date:** Oct 20, 2024  
**Class:** DSC540-T302 Data Preparation  
**Professor:** Professor Williams

## Cleaning/Formatting Flat File Source
Perform at least 5 data transformation and/or cleansing steps to your flat file data. The below examples are not required - they are just potential transformations you could do. If your data doesn't work for these scenarios, complete different transformations. You can do the same transformation multiple times if needed to clean your data. The goal is a clean dataset at the end of the milestone.

Examples:
1. replace headers
2. format data
3. id outliers and bad data
4. find duplicates
5. fix casing or inconsistent values
6. conduct fuzzy matching

# Introduction

The data imported from The CDC Natality Data supresses values that do not meet the criteria for confidentiality constraints.  Navigating this made it difficult to download just one file. Therefore, I loaded multiple data files.  Another issue I faced
was that the request for the data sets could not return anything with more than 75,000 rows.  Therefore, I focused on linking the data together with the census regions and division from the united states census burreau and focused on the year of death as 2022.
The CDC Natalilty Data request form allows up to to 5 variables to be downaloaded at a time. Due to the constraints of the data the main focus of this project will be pre and gestational daibetes, pre and gestational hypertension, eclampsia, previous preterm birth, gonorrhea, shyphilis, chlamydia, hep B, hep C, and Nicotine. The selected pregnancy risk factors were filtered before downloading to fit the constraints and criteria of extraction from the CDC natality data site, with each pregnancy risk factors filtered out for 'Yes' values. It's also important to note that:

- Message  Rows with zero Deaths are hidden, but the Births values in those rows are included in the totals. Use Quick Options above to show zero rows.- 
Message  Rows with suppressed Deaths are hidden, but the Deaths and Births values in those rows are included in the totals..

Columns:  Census Region, Census Region code, pregnancy risk factor, cause of death code, death, births, and death rate

- **Census Region 1 - Northeast:**
  - **Division 1 - New England:** Connecticut, Maine, Massachusetts, New Hampshire, Rhode Island, Vermont.
  - **Division 2 - Middle Atlantic:** New Jersey, New York, Pennsylvania.
  
- **Census Region 2 - Midwest:**
  - **Division 3 - East North Central:** Illinois, Indiana, Michigan, Ohio, Wisconsin.
  - **Division 4 - West North Central:** Iowa, Kansas, Minnesota, Missouri, Nebraska, North Dakota, South Dakota.
  
- **Census Region 3 - South:**
  - **Division 5 - South Atlantic:** Delaware, District of Columbia reporting area, Florida, Georgia, Maryland, North Carolina, South Carolina, Virginia, West Virginia.
  - **Division 6 - East South Central:** Alabama, Kentucky, Mississippi, Tennessee.
  - **Division 7 - West South Central:** Arkansas, Louisiana, Oklahoma, Texas.
  
- **Census Region 4 - West:**
  - **Division 8 - Mountain:** Arizona, Colorado, Idaho, Montana, Nevada, New Mexico, Utah, Wyoming.
  - **Division 9 - Pacific:** Alaska, California, Hawaii, Oregn, Washington.
shington.

In [5]:
# import library
import pandas as pd

# Loading files

## Pre-pregnancy Diabetes

In [9]:
# load pre-pregnancy diabetes file

file_path = 'Project data sets/Pre-pregnancy diabetes cause of death.txt'

# Load the data, specifying the tab delimiter since the columns are separated by tabs
pre_diabetes = pd.read_csv(file_path, delimiter='\t')

# Display the first few rows
pre_diabetes.head()

,Notes,Census Region,Census Region Code,Pre-pregnancy Diabetes,Pre-pregnancy Diabetes Code,Cause of death,Cause of death Code,Deaths,Births,Death Rate
0,Total,Census Region 1: Northeast,CENS-R1,Yes,1.0,NaN,NaN,60.0,6580.0,9.12
1,Total,Census Region 1: Northeast,CENS-R1,NaN,NaN,NaN,NaN,60.0,6580.0,9.12
2,NaN,Census Region 2: Midwest,CENS-R2,Yes,1.0,Extreme immaturity,P07.2,12.0,9438.0,1.27 (Unreliable)
3,Total,Census Region 2: Midwest,CENS-R2,Yes,1.0,NaN,NaN,103.0,9438.0,10.91
4,Total,Census Region 2: Midwest,CENS-R2,NaN,NaN,NaN,NaN,103.0,9438.0,10.91

## Gestational Diabetes

In [12]:
# load gestational diabetes file

file_path = 'Project data sets/Gestational diabetes cause of death.txt'

# Load the data, specifying the tab delimiter since the columns are separated by tabs
ges_diabetes = pd.read_csv(file_path, delimiter='\t')

# Display the first few rows
ges_diabetes.head()

,Notes,Census Region,Census Region Code,Gestational Diabetes,Gestational Diabetes Code,Cause of death,Cause of death Code,Deaths,Births,Death Rate
0,NaN,Census Region 1: Northeast,CENS-R1,Yes,1.0,Sudden infant death syndrome - SIDS,R95,19.0,50851.0,0.37 (Unreliable)
1,Total,Census Region 1: Northeast,CENS-R1,Yes,1.0,NaN,NaN,129.0,50851.0,2.54
2,Total,Census Region 1: Northeast,CENS-R1,NaN,NaN,NaN,NaN,129.0,50851.0,2.54
3,NaN,Census Region 2: Midwest,CENS-R2,Yes,1.0,Extreme immaturity,P07.2,13.0,64914.0,0.20 (Unreliable)
4,NaN,Census Region 2: Midwest,CENS-R2,Yes,1.0,Hypoxic ischemic encephalopathy of newborn,P91.6,10.0,64914.0,0.15 (Unreliable)

## Pre-pregnancy Hypertension

In [15]:
# Load pre-pregnancy hypertension file

file_path = 'Project data sets/Pre-pregnancy hypertension cause of death.txt'

# Load the data, specifying the tab delimiter since the columns are separated by tabs
pre_hypertension = pd.read_csv(file_path, delimiter='\t')

# Display the first few rows
pre_hypertension.head()

,Notes,Census Region,Census Region Code,Pre-pregnancy Hypertension,Pre-pregnancy Hypertension Code,Cause of death,Cause of death Code,Deaths,Births,Death Rate
0,NaN,Census Region 1: Northeast,CENS-R1,Yes,1.0,Extreme immaturity,P07.2,13.0,18064.0,0.72 (Unreliable)
1,NaN,Census Region 1: Northeast,CENS-R1,Yes,1.0,Respiratory distress syndrome of newborn,P22.0,10.0,18064.0,0.55 (Unreliable)
2,NaN,Census Region 1: Northeast,CENS-R1,Yes,1.0,Sudden infant death syndrome - SIDS,R95,10.0,18064.0,0.55 (Unreliable)
3,Total,Census Region 1: Northeast,CENS-R1,Yes,1.0,NaN,NaN,132.0,18064.0,7.31
4,Total,Census Region 1: Northeast,CENS-R1,NaN,NaN,NaN,NaN,132.0,18064.0,7.31

## Gestational Hypertension

In [18]:
# Load gestational hypertension file

file_path = 'Project data sets/Gestational hypertension cause of death.txt'

# Load the data, specifying the tab delimiter since the columns are separated by tabs
ges_hypertension = pd.read_csv(file_path, delimiter='\t')

# Display the first few rows
ges_hypertension.head()

,Notes,Census Region,Census Region Code,Gestational Hypertension,Gestational Hypertension Code,Cause of death,Cause of death Code,Deaths,Births,Death Rate
0,NaN,Census Region 1: Northeast,CENS-R1,Yes,1.0,Extreme immaturity,P07.2,10.0,50171.0,0.20 (Unreliable)
1,NaN,Census Region 1: Northeast,CENS-R1,Yes,1.0,Sudden infant death syndrome - SIDS,R95,28.0,50171.0,0.56
2,NaN,Census Region 1: Northeast,CENS-R1,Yes,1.0,Other ill-defined and unspecified causes of mo...,R99,14.0,50171.0,0.28 (Unreliable)
3,NaN,Census Region 1: Northeast,CENS-R1,Yes,1.0,Accidental suffocation and strangulation in bed,W75,10.0,50171.0,0.20 (Unreliable)
4,Total,Census Region 1: Northeast,CENS-R1,Yes,1.0,NaN,NaN,228.0,50171.0,4.54

## Eclampsia

In [21]:
# Load eclampsia file

file_path = 'Project data sets/eclampsia cause of death.txt'

# Load the data, specifying the tab delimiter since the columns are separated by tabs
eclampsia = pd.read_csv(file_path, delimiter='\t')

# Display the first few rows
eclampsia.head()

,Notes,Census Region,Census Region Code,Eclampsia,Eclampsia Code,Cause of death,Cause of death Code,Deaths,Births,Death Rate
0,Total,Census Region 2: Midwest,CENS-R2,Yes,1.0,NaN,NaN,18.0,2029.0,8.87 (Unreliable)
1,Total,Census Region 2: Midwest,CENS-R2,NaN,NaN,NaN,NaN,18.0,2029.0,8.87 (Unreliable)
2,Total,Census Region 3: South,CENS-R3,Yes,1.0,NaN,NaN,46.0,3280.0,14.02
3,Total,Census Region 3: South,CENS-R3,NaN,NaN,NaN,NaN,46.0,3280.0,14.02
4,Total,Census Region 4: West,CENS-R4,Yes,1.0,NaN,NaN,25.0,3151.0,7.93

## Previous pre-term birth

In [24]:
# Load previous pre-term birth file

file_path = 'Project data sets/Previous Preterm birth cause of death.txt'

# Load the data, specifying the tab delimiter since the columns are separated by tabs
prev_preterm = pd.read_csv(file_path, delimiter='\t')

# Display the first few rows
prev_preterm.head()

,Notes,Census Region,Census Region Code,Previous Preterm Birth,Previous Preterm Birth Code,Cause of death,Cause of death Code,Deaths,Births,Death Rate
0,NaN,Census Region 1: Northeast,CENS-R1,Yes,1.0,Newborn affected by incompetent cervix,P01.0,11.0,24231.0,0.45 (Unreliable)
1,NaN,Census Region 1: Northeast,CENS-R1,Yes,1.0,Extreme immaturity,P07.2,25.0,24231.0,1.03
2,NaN,Census Region 1: Northeast,CENS-R1,Yes,1.0,Respiratory distress syndrome of newborn,P22.0,14.0,24231.0,0.58 (Unreliable)
3,NaN,Census Region 1: Northeast,CENS-R1,Yes,1.0,Neonatal cardiac dysrhythmia,P29.1,12.0,24231.0,0.50 (Unreliable)
4,NaN,Census Region 1: Northeast,CENS-R1,Yes,1.0,"Bacterial sepsis of newborn, unspecified",P36.9,10.0,24231.0,0.41 (Unreliable)

## Gonorhea

In [27]:
# Load Gonorrhea file

file_path = 'Project data sets/Gonorrhea cause of death.txt'

# Load the data, specifying the tab delimiter since the columns are separated by tabs
gonorrhea = pd.read_csv(file_path, delimiter='\t')

# Display the first few rows
gonorrhea.head()

,Notes,Census Region,Census Region Code,Gonorrhea,Gonorrhea Code,Cause of death,Cause of death Code,Deaths,Births,Death Rate
0,Total,Census Region 1: Northeast,CENS-R1,Yes,1.0,NaN,NaN,16.0,1025.0,15.61 (Unreliable)
1,Total,Census Region 1: Northeast,CENS-R1,NaN,NaN,NaN,NaN,16.0,1025.0,15.61 (Unreliable)
2,NaN,Census Region 2: Midwest,CENS-R2,Yes,1.0,Accidental suffocation and strangulation in bed,W75,10.0,2740.0,3.65 (Unreliable)
3,Total,Census Region 2: Midwest,CENS-R2,Yes,1.0,NaN,NaN,47.0,2740.0,17.15
4,Total,Census Region 2: Midwest,CENS-R2,NaN,NaN,NaN,NaN,47.0,2740.0,17.15

## Syphilis

In [30]:
# Load Syphilis file

file_path = 'Project data sets/Syphilis cause of death.txt'

# Load the data, specifying the tab delimiter since the columns are separated by tabs
syphilis = pd.read_csv(file_path, delimiter='\t')

# Display the first few rows
syphilis.head()

,Notes,Census Region,Census Region Code,Syphilis,Syphilis Code,Cause of death,Cause of death Code,Deaths,Births,Death Rate
0,Total,Census Region 1: Northeast,CENS-R1,Yes,1.0,NaN,NaN,14.0,1053.0,13.30 (Unreliable)
1,Total,Census Region 1: Northeast,CENS-R1,NaN,NaN,NaN,NaN,14.0,1053.0,13.30 (Unreliable)
2,Total,Census Region 2: Midwest,CENS-R2,Yes,1.0,NaN,NaN,20.0,1928.0,10.37
3,Total,Census Region 2: Midwest,CENS-R2,NaN,NaN,NaN,NaN,20.0,1928.0,10.37
4,NaN,Census Region 3: South,CENS-R3,Yes,1.0,Sudden infant death syndrome - SIDS,R95,10.0,4898.0,2.04 (Unreliable)

## Chlamydia

In [33]:
# Load Chlamydia file

file_path = 'Project data sets/Chlamydia cause of death.txt'

# Load the data, specifying the tab delimiter since the columns are separated by tabs
chlamydia = pd.read_csv(file_path, delimiter='\t')

# Display the first few rows
chlamydia.head()

,Notes,Census Region,Census Region Code,Chlamydia,Chlamydia Code,Cause of death,Cause of death Code,Deaths,Births,Death Rate
0,NaN,Census Region 1: Northeast,CENS-R1,Yes,1.0,Other ill-defined and unspecified causes of mo...,R99,14.0,7743.0,1.81 (Unreliable)
1,Total,Census Region 1: Northeast,CENS-R1,Yes,1.0,NaN,NaN,60.0,7743.0,7.75
2,Total,Census Region 1: Northeast,CENS-R1,NaN,NaN,NaN,NaN,60.0,7743.0,7.75
3,NaN,Census Region 2: Midwest,CENS-R2,Yes,1.0,Extreme immaturity,P07.2,13.0,14093.0,0.92 (Unreliable)
4,NaN,Census Region 2: Midwest,CENS-R2,Yes,1.0,Sudden infant death syndrome - SIDS,R95,14.0,14093.0,0.99 (Unreliable)

## Hepatitis B

In [36]:
# Load Hep B file

file_path = 'Project data sets/Hep B cause of death.txt'

# Load the data, specifying the tab delimiter since the columns are separated by tabs
hep_B = pd.read_csv(file_path, delimiter='\t')

# Display the first few rows
hep_B.head()

,Notes,Census Region,Census Region Code,Hepatitis B,Hepatitis B Code,Cause of death,Cause of death Code,Deaths,Births,Death Rate
0,Total,Census Region 3: South,CENS-R3,Yes,1.0,NaN,NaN,18.0,1764.0,10.20 (Unreliable)
1,Total,Census Region 3: South,CENS-R3,NaN,NaN,NaN,NaN,18.0,1764.0,10.20 (Unreliable)
2,Total,NaN,NaN,NaN,NaN,NaN,NaN,38.0,6096.0,6.23
3,---,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,"Dataset: Linked Birth / Infant Death Records, ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Hepatitis C

In [39]:
# Load Hepatitis C file

file_path = 'Project data sets/Hep C cause of death.txt'

# Load the data, specifying the tab delimiter since the columns are separated by tabs
hep_C = pd.read_csv(file_path, delimiter='\t')

# Display the first few rows
hep_C.head()

,Notes,Census Region,Census Region Code,Hepatitis C,Hepatitis C Code,Cause of death,Cause of death Code,Deaths,Births,Death Rate
0,Total,Census Region 1: Northeast,CENS-R1,Yes,1.0,NaN,NaN,27.0,3100.0,8.71
1,Total,Census Region 1: Northeast,CENS-R1,NaN,NaN,NaN,NaN,27.0,3100.0,8.71
2,Total,Census Region 2: Midwest,CENS-R2,Yes,1.0,NaN,NaN,52.0,4031.0,12.90
3,Total,Census Region 2: Midwest,CENS-R2,NaN,NaN,NaN,NaN,52.0,4031.0,12.90
4,NaN,Census Region 3: South,CENS-R3,Yes,1.0,Sudden infant death syndrome - SIDS,R95,14.0,6309.0,2.22 (Unreliable)

## Nicotine

In [42]:
# Load Tobacco use file

file_path = 'Project data sets/Tobacco Use cause of death.txt'

# Load the data, specifying the tab delimiter since the columns are separated by tabs
nicotine = pd.read_csv(file_path, delimiter='\t')

# Display the first few rows
nicotine.head()

,Notes,Census Region,Census Region Code,Tobacco Use,Tobacco Use Code,Cause of death,Cause of death Code,Deaths,Births,Death Rate
0,NaN,Census Region 1: Northeast,CENS-R1,Yes,1.0,Sudden infant death syndrome - SIDS,R95,41.0,18684.0,2.19
1,NaN,Census Region 1: Northeast,CENS-R1,Yes,1.0,Other ill-defined and unspecified causes of mo...,R99,27.0,18684.0,1.45
2,NaN,Census Region 1: Northeast,CENS-R1,Yes,1.0,Accidental suffocation and strangulation in bed,W75,16.0,18684.0,0.86 (Unreliable)
3,Total,Census Region 1: Northeast,CENS-R1,Yes,1.0,NaN,NaN,220.0,18684.0,11.77
4,Total,Census Region 1: Northeast,CENS-R1,NaN,NaN,NaN,NaN,220.0,18684.0,11.77

## Number One Drug Used For Conditions Satisfied

In [45]:
# Load Tobacco use file

file_path = 'Project data sets/pregnancy_conditions_common_drugs.csv'  # Replace with the actual file path
nicotine = pd.read_csv(file_path)

# Display the first few rows
nicotine.head()

                    Condition Number One Drug Used FDA Pregnancy Risk Category
0      Pre-Pregnancy Diabetes              Insulin                           A
1        Gestational Diabetes              Insulin                           A
2  Pre-Pregnancy Hypertension            Labetalol                           C
3    Gestational Hypertension            Labetalol                           C
4                   Eclampsia    Magnesium sulfate                           A

## 1. Combine Files

Use folder path to merge all the necessary data in order join all of the necessary txt files needed for analysis

In [48]:
import os

# Specify the folder containing the .txt files
folder_path = 'Project data sets'  # Replace with the actual folder path

# Get a list of all .txt files in the folder
txt_files = [file for file in os.listdir(folder_path) if file.endswith('.txt')]

# Create an empty list to store DataFrames
df_list = []

# Loop through each file and read it into a DataFrame
for file in txt_files:
    file_path = os.path.join(folder_path, file)
    df = pd.read_csv(file_path, delimiter='\t')  
    df_list.append(df)

# Concatenate all DataFrames into one
combined_df = pd.concat(df_list, ignore_index=True)

# Display the first few rows of the combined DataFrame
combined_df.head()

,Notes,Census Region,Census Region Code,Chlamydia,Chlamydia Code,Cause of death,Cause of death Code,Deaths,Births,Death Rate,...,Pre-pregnancy Diabetes,Pre-pregnancy Diabetes Code,Pre-pregnancy Hypertension,Pre-pregnancy Hypertension Code,Previous Preterm Birth,Previous Preterm Birth Code,Syphilis,Syphilis Code,Tobacco Use,Tobacco Use Code
0,NaN,Census Region 1: Northeast,CENS-R1,Yes,1.0,Other ill-defined and unspecified causes of mo...,R99,14.0,7743.0,1.81 (Unreliable),...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Total,Census Region 1: Northeast,CENS-R1,Yes,1.0,NaN,NaN,60.0,7743.0,7.75,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Total,Census Region 1: Northeast,CENS-R1,NaN,NaN,NaN,NaN,60.0,7743.0,7.75,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,Census Region 2: Midwest,CENS-R2,Yes,1.0,Extreme immaturity,P07.2,13.0,14093.0,0.92 (Unreliable),...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,Census Region 2: Midwest,CENS-R2,Yes,1.0,Sudden infant death syndrome - SIDS,R95,14.0,14093.0,0.99 (Unreliable),...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [138]:
# Check original Census Regions 

# Get unique values in the 'Census Region' column
unique_census_regions = combined_df['Census Region'].unique()

# Display the unique values
print("Unique Census Regions:")
print(unique_census_regions)

Unique Census Regions:
['Census Region 1: Northeast' 'Census Region 2: Midwest'
 'Census Region 3: South' 'Census Region 4: West' nan]

## 2. Remove Unnecessary Rows

The combined data includes unnecessary rows that show information not needed for analysis

In [64]:
# Check for missing values in each column
missing_values = combined_df.isna().sum()

# Display columns with missing values
print(missing_values)

Notes                              154
Census Region                      483
Census Region Code                 483
Chlamydia                          713
Chlamydia Code                     713
Cause of death                     571
Cause of death Code                571
Deaths                             471
Births                             471
Death Rate                         471
Eclampsia                          722
Eclampsia Code                     722
Gestational Diabetes               703
Gestational Diabetes Code          703
Gestational Hypertension           679
Gestational Hypertension Code      679
Gonorrhea                          718
Gonorrhea Code                     718
Hepatitis B                        724
Hepatitis B Code                   724
Hepatitis C                        720
Hepatitis C Code                   720
Pre-pregnancy Diabetes             718
Pre-pregnancy Diabetes Code        718
Pre-pregnancy Hypertension         703
Pre-pregnancy Hypertension Code    703
Previous Preterm Birth             685
Previous Preterm Birth Code        685
Syphilis                           720
Syphilis Code                      720
Tobacco Use                        697
Tobacco Use Code                   697
dtype: int64

In [66]:
# Remove Rows with Missing or Empty Census Region
# Remove rows where "Census Region" is NaN
df_cleaned = combined_df.dropna(subset=['Census Region'])

# Display the cleaned DataFrame
df_cleaned.head()

,Notes,Census Region,Census Region Code,Chlamydia,Chlamydia Code,Cause of death,Cause of death Code,Deaths,Births,Death Rate,...,Pre-pregnancy Diabetes,Pre-pregnancy Diabetes Code,Pre-pregnancy Hypertension,Pre-pregnancy Hypertension Code,Previous Preterm Birth,Previous Preterm Birth Code,Syphilis,Syphilis Code,Tobacco Use,Tobacco Use Code
0,NaN,Census Region 1: Northeast,CENS-R1,Yes,1.0,Other ill-defined and unspecified causes of mo...,R99,14.0,7743.0,1.81 (Unreliable),...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Total,Census Region 1: Northeast,CENS-R1,Yes,1.0,NaN,NaN,60.0,7743.0,7.75,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Total,Census Region 1: Northeast,CENS-R1,NaN,NaN,NaN,NaN,60.0,7743.0,7.75,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,Census Region 2: Midwest,CENS-R2,Yes,1.0,Extreme immaturity,P07.2,13.0,14093.0,0.92 (Unreliable),...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,Census Region 2: Midwest,CENS-R2,Yes,1.0,Sudden infant death syndrome - SIDS,R95,14.0,14093.0,0.99 (Unreliable),...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [68]:
# check NaN again of cleaned df
cleaned_NaN = df_cleaned.isna().sum()
# Display columns with missing values
print(cleaned_NaN)

Notes                              154
Census Region                        0
Census Region Code                   0
Chlamydia                          230
Chlamydia Code                     230
Cause of death                      88
Cause of death Code                 88
Deaths                               0
Births                               0
Death Rate                           0
Eclampsia                          239
Eclampsia Code                     239
Gestational Diabetes               220
Gestational Diabetes Code          220
Gestational Hypertension           196
Gestational Hypertension Code      196
Gonorrhea                          235
Gonorrhea Code                     235
Hepatitis B                        241
Hepatitis B Code                   241
Hepatitis C                        237
Hepatitis C Code                   237
Pre-pregnancy Diabetes             235
Pre-pregnancy Diabetes Code        235
Pre-pregnancy Hypertension         220
Pre-pregnancy Hypertension Code    220
Previous Preterm Birth             202
Previous Preterm Birth Code        202
Syphilis                           237
Syphilis Code                      237
Tobacco Use                        214
Tobacco Use Code                   214
dtype: int64

## 3. Remove unnecessary columns

The combined data includes unnecessary columns for analysis, therefore they are removed.

In [74]:
# Remove whitespace from column names
df_cleaned.columns = df_cleaned.columns.str.strip()

# Specify the columns to remove
columns_to_remove = ['Chlamydia Code', 'Eclampsia Code', 'Gestational Diabetes Code', 
                     'Gestational Hypertension Code', 'Gonorrhea Code', 'Hepatitis B Code', 
                     'Hepatitis C Code', 'Pre-pregnancy Diabetes Code', 
                     'Pre-pregnancy Hypertension Code', 'Previous Preterm Birth Code', 
                     'Syphilis Code', 'Tobacco Use Code', 'Cause of death Code']

# Check which columns exist and drop them
existing_columns_to_remove = [col for col in columns_to_remove if col in df_cleaned.columns]
df_cleaned2 = df_cleaned.drop(columns=existing_columns_to_remove)

In [76]:
# Display the NaN of the cleaned df
print(df_cleaned2.isna().sum())

Notes                         154
Census Region                   0
Census Region Code              0
Chlamydia                     230
Cause of death                 88
Deaths                          0
Births                          0
Death Rate                      0
Eclampsia                     239
Gestational Diabetes          220
Gestational Hypertension      196
Gonorrhea                     235
Hepatitis B                   241
Hepatitis C                   237
Pre-pregnancy Diabetes        235
Pre-pregnancy Hypertension    220
Previous Preterm Birth        202
Syphilis                      237
Tobacco Use                   214
dtype: int64

## 3. Deal with missing values

Since the data is compiled from different extraction processes from the CDC natality data, missing values can be replaced with unknown in order to not get rid of necessary columns for the analysis.

In [78]:
# List of columns to replace missing values with "unknown"
columns_to_fill = ['Chlamydia', 'Eclampsia', 'Gestational Diabetes', 
                   'Gestational Hypertension', 'Gonorrhea', 'Hepatitis B', 
                   'Hepatitis C', 'Pre-pregnancy Diabetes', 
                   'Pre-pregnancy Hypertension', 'Previous Preterm Birth', 
                   'Syphilis', 'Tobacco Use', 'Cause of death']

# Fill missing values in the specified columns with "unknown"
df_cleaned2[columns_to_fill] = df_cleaned2[columns_to_fill].fillna("unknown")

# display new missing values
print(df_cleaned2.isna().sum())

Notes                         154
Census Region                   0
Census Region Code              0
Chlamydia                       0
Cause of death                  0
Deaths                          0
Births                          0
Death Rate                      0
Eclampsia                       0
Gestational Diabetes            0
Gestational Hypertension        0
Gonorrhea                       0
Hepatitis B                     0
Hepatitis C                     0
Pre-pregnancy Diabetes          0
Pre-pregnancy Hypertension      0
Previous Preterm Birth          0
Syphilis                        0
Tobacco Use                     0
dtype: int64

In [80]:
# Print the first five rows of df_cleaned2
print(df_cleaned2.head())

   Notes               Census Region Census Region Code Chlamydia  \
0    NaN  Census Region 1: Northeast            CENS-R1       Yes
1  Total  Census Region 1: Northeast            CENS-R1       Yes
2  Total  Census Region 1: Northeast            CENS-R1   unknown
3    NaN    Census Region 2: Midwest            CENS-R2       Yes
4    NaN    Census Region 2: Midwest            CENS-R2       Yes

                                      Cause of death  Deaths   Births  \
0  Other ill-defined and unspecified causes of mo...    14.0   7743.0
1                                            unknown    60.0   7743.0
2                                            unknown    60.0   7743.0
3                                 Extreme immaturity    13.0  14093.0
4                Sudden infant death syndrome - SIDS    14.0  14093.0

          Death Rate Eclampsia Gestational Diabetes Gestational Hypertension  \
0  1.81 (Unreliable)   unknown              unknown                  unknown
1               7.75   unknown              unknown                  unknown
2               7.75   unknown              unknown                  unknown
3  0.92 (Unreliable)   unknown              unknown                  unknown
4  0.99 (Unreliable)   unknown              unknown                  unknown

  Gonorrhea Hepatitis B Hepatitis C Pre-pregnancy Diabetes  \
0   unknown     unknown     unknown                unknown
1   unknown     unknown     unknown                unknown
2   unknown     unknown     unknown                unknown
3   unknown     unknown     unknown                unknown
4   unknown     unknown     unknown                unknown

  Pre-pregnancy Hypertension Previous Preterm Birth Syphilis Tobacco Use
0                    unknown                unknown  unknown     unknown
1                    unknown                unknown  unknown     unknown
2                    unknown                unknown  unknown     unknown
3                    unknown                unknown  unknown     unknown
4                    unknown                unknown  unknown     unknown

## 4. Create new data frame for Total 

The 'Total' values in Notes column are their own separate values and requires it's own DF in order to work with it.

### Getting to know the cleaned data frame

In [93]:
# Display information about df_cleaned2
df_cleaned2.info()

<class 'pandas.core.frame.DataFrame'>
Index: 242 entries, 0 to 684
Data columns (total 19 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Notes                       88 non-null     object
 1   Census Region               242 non-null    object
 2   Census Region Code          242 non-null    object
 3   Chlamydia                   242 non-null    object
 4   Cause of death              242 non-null    object
 5   Deaths                      242 non-null    float64
 6   Births                      242 non-null    float64
 7   Death Rate                  242 non-null    object
 8   Eclampsia                   242 non-null    object
 9   Gestational Diabetes        242 non-null    object
 10  Gestational Hypertension    242 non-null    object
 11  Gonorrhea                   242 non-null    object
 12  Hepatitis B                 242 non-null    object
 13  Hepatitis C                 242 non-null    object
 14  Pre-pregnancy Diabetes      242 non-null    object
 15  Pre-pregnancy Hypertension  242 non-null    object
 16  Previous Preterm Birth      242 non-null    object
 17  Syphilis                    242 non-null    object
 18  Tobacco Use                 242 non-null    object
dtypes: float64(2), object(17)
memory usage: 37.8+ KB

In [103]:
# How many data points are there for list of health-related columns? 
health_columns = [
    'Chlamydia', 'Eclampsia', 'Gestational Diabetes', 'Gestational Hypertension',
    'Gonorrhea', 'Hepatitis B', 'Hepatitis C', 'Pre-pregnancy Diabetes',
    'Pre-pregnancy Hypertension', 'Previous Preterm Birth', 'Syphilis', 'Tobacco Use'
]

# Step 1: Count the number of "Yes" values in each column
yes_counts = df_cleaned2[health_columns].apply(lambda col: (col == 'Yes').sum())

# Step 2: Display the total "Yes" counts for each column
print(yes_counts)

Chlamydia                     12
Eclampsia                      3
Gestational Diabetes          22
Gestational Hypertension      46
Gonorrhea                      7
Hepatitis B                    1
Hepatitis C                    5
Pre-pregnancy Diabetes         7
Pre-pregnancy Hypertension    22
Previous Preterm Birth        40
Syphilis                       5
Tobacco Use                   28
dtype: int64

In [105]:
# How many times does "Total" appear in "Notes" column

# Count the occurrences of "Total" in the "Notes" column
total_count = df_cleaned2['Notes'].str.contains('Total', na=False).sum()

# Display the count
print(f'Total occurrences of "Total" in Notes: {total_count}')

Total occurrences of "Total" in Notes: 88

In [112]:
# Get unique values in the "Census Region" column
unique_census_regions = df_cleaned2['Census Region'].unique()

# Display the unique Census Region values
print(unique_census_regions)

['Census Region 1: Northeast' 'Census Region 2: Midwest'
 'Census Region 3: South' 'Census Region 4: West']

In [108]:
# How many total entries are there for each "census region"

# Count non-null values for each Census Region in specific columns
census_region_variable_counts = df_cleaned2.groupby('Census Region').count()

# Display the result
print(census_region_variable_counts)

                            Notes  Census Region Code  Chlamydia  \
Census Region
Census Region 1: Northeast     20                  39         39
Census Region 2: Midwest       22                  68         68
Census Region 3: South         24                  95         95
Census Region 4: West          22                  40         40

                            Cause of death  Deaths  Births  Death Rate  \
Census Region
Census Region 1: Northeast              39      39      39          39
Census Region 2: Midwest                68      68      68          68
Census Region 3: South                  95      95      95          95
Census Region 4: West                   40      40      40          40

                            Eclampsia  Gestational Diabetes  \
Census Region
Census Region 1: Northeast         39                    39
Census Region 2: Midwest           68                    68
Census Region 3: South             95                    95
Census Region 4: West              40                    40

                            Gestational Hypertension  Gonorrhea  Hepatitis B  \
Census Region
Census Region 1: Northeast                        39         39           39
Census Region 2: Midwest                          68         68           68
Census Region 3: South                            95         95           95
Census Region 4: West                             40         40           40

                            Hepatitis C  Pre-pregnancy Diabetes  \
Census Region
Census Region 1: Northeast           39                      39
Census Region 2: Midwest             68                      68
Census Region 3: South               95                      95
Census Region 4: West                40                      40

                            Pre-pregnancy Hypertension  \
Census Region
Census Region 1: Northeast                          39
Census Region 2: Midwest                            68
Census Region 3: South                              95
Census Region 4: West                               40

                            Previous Preterm Birth  Syphilis  Tobacco Use
Census Region
Census Region 1: Northeast                      39        39           39
Census Region 2: Midwest                        68        68           68
Census Region 3: South                          95        95           95
Census Region 4: West                           40        40           40

In [110]:
# How bout Census region code?
# Count the number of occurrences of each unique Census Region Code
census_region_code_counts = df_cleaned2.groupby('Census Region Code').size()

# Display the result
print(census_region_code_counts)

Census Region Code
CENS-R1    39
CENS-R2    68
CENS-R3    95
CENS-R4    40
dtype: int64

In [129]:
# Create a new DataFrame with rows where "Notes" contains "Total"
df_total_notes = df_cleaned2[df_cleaned2['Notes'].str.contains("Total", na=False)]

# Optional: Reset the index of the new DataFrame
df_total_notes.reset_index(drop=True, inplace=True)

# Display the new DataFrame
df_total_notes.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 88 entries, 0 to 87
Data columns (total 19 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Notes                       88 non-null     object
 1   Census Region               88 non-null     object
 2   Census Region Code          88 non-null     object
 3   Chlamydia                   88 non-null     object
 4   Cause of death              88 non-null     object
 5   Deaths                      88 non-null     float64
 6   Births                      88 non-null     float64
 7   Death Rate                  88 non-null     object
 8   Eclampsia                   88 non-null     object
 9   Gestational Diabetes        88 non-null     object
 10  Gestational Hypertension    88 non-null     object
 11  Gonorrhea                   88 non-null     object
 12  Hepatitis B                 88 non-null     object
 13  Hepatitis C                 88 non-null     object
 14  Pre-pregnancy Diabetes      88 non-null     object
 15  Pre-pregnancy Hypertension  88 non-null     object
 16  Previous Preterm Birth      88 non-null     object
 17  Syphilis                    88 non-null     object
 18  Tobacco Use                 88 non-null     object
dtypes: float64(2), object(17)
memory usage: 13.2+ KB

## 5. Check for duplicates and Save Data frame as CSV

no duplicates found in the final dataframes

In [136]:
# Check for duplicate rows in the entire df_total_notes
duplicates = df_total_notes[df_total_notes.duplicated()]

# Display the duplicate rows
print("Duplicate Rows based on all columns:")
print(duplicates)

Duplicate Rows based on all columns:
Empty DataFrame
Columns: [Notes, Census Region, Census Region Code, Chlamydia, Cause of death, Deaths, Births, Death Rate, Eclampsia, Gestational Diabetes, Gestational Hypertension, Gonorrhea, Hepatitis B, Hepatitis C, Pre-pregnancy Diabetes, Pre-pregnancy Hypertension, Previous Preterm Birth, Syphilis, Tobacco Use]
Index: []

In [144]:
# Check for duplicates 
# Check for duplicate rows in the entire DataFrame
duplicates = df_cleaned2[combined_df.duplicated()]

# Display the duplicate rows
print("Duplicate Rows based on all columns:")
print(duplicates)

Duplicate Rows based on all columns:
Empty DataFrame
Columns: [Notes, Census Region, Census Region Code, Chlamydia, Cause of death, Deaths, Births, Death Rate, Eclampsia, Gestational Diabetes, Gestational Hypertension, Gonorrhea, Hepatitis B, Hepatitis C, Pre-pregnancy Diabetes, Pre-pregnancy Hypertension, Previous Preterm Birth, Syphilis, Tobacco Use]
Index: []

C:\Users\samue\AppData\Local\Temp\ipykernel_7816\3464625603.py:3: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  duplicates = df_cleaned2[combined_df.duplicated()]

In [152]:
# Format Final Files as CSV and download

# Save df_total_notes to a CSV file
df_total_notes.to_csv('df_total_notes.csv', index=False)

# Save df_cleaned2 to a CSV file
df_cleaned2.to_csv('df_cleaned2.csv', index=False)

After futher evaluation of the df_total_notes file. Each value is repeated twice. So I need to go in and delete every uneven row starting at row 3

In [158]:
# Load the DataFrame from the CSV file
df_total_notes = pd.read_csv('df_total_notes.csv')

# Display the original DataFrame
print("Original DataFrame:")
print(df_total_notes)

# Delete each uneven row starting at index 2 (which is the 3rd row)
# Keeping only even indexed rows from index 2 onwards
df_total_cleaned = df_total_notes.iloc[2::2].reset_index(drop=True)

# Display the cleaned DataFrame
print("DataFrame after deleting uneven rows starting at index 2:")
print(df_total_cleaned)

Original DataFrame:
    Notes               Census Region Census Region Code Chlamydia  \
0   Total  Census Region 1: Northeast            CENS-R1       Yes
1   Total  Census Region 1: Northeast            CENS-R1   unknown
2   Total    Census Region 2: Midwest            CENS-R2       Yes
3   Total    Census Region 2: Midwest            CENS-R2   unknown
4   Total      Census Region 3: South            CENS-R3       Yes
..    ...                         ...                ...       ...
83  Total    Census Region 2: Midwest            CENS-R2   unknown
84  Total      Census Region 3: South            CENS-R3   unknown
85  Total      Census Region 3: South            CENS-R3   unknown
86  Total       Census Region 4: West            CENS-R4   unknown
87  Total       Census Region 4: West            CENS-R4   unknown

   Cause of death  Deaths   Births Death Rate Eclampsia Gestational Diabetes  \
0         unknown    60.0   7743.0       7.75   unknown              unknown
1         unknown    60.0   7743.0       7.75   unknown              unknown
2         unknown   143.0  14093.0      10.15   unknown              unknown
3         unknown   143.0  14093.0      10.15   unknown              unknown
4         unknown   256.0  30595.0       8.37   unknown              unknown
..            ...     ...      ...        ...       ...                  ...
83        unknown   540.0  45140.0      11.96   unknown              unknown
84        unknown   696.0  53564.0      12.99   unknown              unknown
85        unknown   696.0  53564.0      12.99   unknown              unknown
86        unknown   171.0  16753.0      10.21   unknown              unknown
87        unknown   171.0  16753.0      10.21   unknown              unknown

   Gestational Hypertension Gonorrhea Hepatitis B Hepatitis C  \
0                   unknown   unknown     unknown     unknown
1                   unknown   unknown     unknown     unknown
2                   unknown   unknown     unknown     unknown
3                   unknown   unknown     unknown     unknown
4                   unknown   unknown     unknown     unknown
..                      ...       ...         ...         ...
83                  unknown   unknown     unknown     unknown
84                  unknown   unknown     unknown     unknown
85                  unknown   unknown     unknown     unknown
86                  unknown   unknown     unknown     unknown
87                  unknown   unknown     unknown     unknown

   Pre-pregnancy Diabetes Pre-pregnancy Hypertension Previous Preterm Birth  \
0                 unknown                    unknown                unknown
1                 unknown                    unknown                unknown
2                 unknown                    unknown                unknown
3                 unknown                    unknown                unknown
4                 unknown                    unknown                unknown
..                    ...                        ...                    ...
83                unknown                    unknown                unknown
84                unknown                    unknown                unknown
85                unknown                    unknown                unknown
86                unknown                    unknown                unknown
87                unknown                    unknown                unknown

   Syphilis Tobacco Use
0   unknown     unknown
1   unknown     unknown
2   unknown     unknown
3   unknown     unknown
4   unknown     unknown
..      ...         ...
83  unknown     unknown
84  unknown         Yes
85  unknown     unknown
86  unknown         Yes
87  unknown     unknown

[88 rows x 19 columns]
DataFrame after deleting uneven rows starting at index 2:
    Notes               Census Region Census Region Code Chlamydia  \
0   Total    Census Region 2: Midwest            CENS-R2       Yes
1   Total      Census Region 3: South            CENS-R3       Yes
2   Total       Census Region 4: West            CENS-R4       Yes
3   Total    Census Region 2: Midwest            CENS-R2   unknown
4   Total      Census Region 3: South            CENS-R3   unknown
5   Total       Census Region 4: West            CENS-R4   unknown
6   Total  Census Region 1: Northeast            CENS-R1   unknown
7   Total    Census Region 2: Midwest            CENS-R2   unknown
8   Total      Census Region 3: South            CENS-R3   unknown
9   Total       Census Region 4: West            CENS-R4   unknown
10  Total  Census Region 1: Northeast            CENS-R1   unknown
11  Total    Census Region 2: Midwest            CENS-R2   unknown
12  Total      Census Region 3: South            CENS-R3   unknown
13  Total       Census Region 4: West            CENS-R4   unknown
14  Total  Census Region 1: Northeast            CENS-R1   unknown
15  Total    Census Region 2: Midwest            CENS-R2   unknown
16  Total      Census Region 3: South            CENS-R3   unknown
17  Total       Census Region 4: West            CENS-R4   unknown
18  Total      Census Region 3: South            CENS-R3   unknown
19  Total  Census Region 1: Northeast            CENS-R1   unknown
20  Total    Census Region 2: Midwest            CENS-R2   unknown
21  Total      Census Region 3: South            CENS-R3   unknown
22  Total       Census Region 4: West            CENS-R4   unknown
23  Total  Census Region 1: Northeast            CENS-R1   unknown
24  Total    Census Region 2: Midwest            CENS-R2   unknown
25  Total      Census Region 3: South            CENS-R3   unknown
26  Total       Census Region 4: West            CENS-R4   unknown
27  Total  Census Region 1: Northeast            CENS-R1   unknown
28  Total    Census Region 2: Midwest            CENS-R2   unknown
29  Total      Census Region 3: South            CENS-R3   unknown
30  Total       Census Region 4: West            CENS-R4   unknown
31  Total  Census Region 1: Northeast            CENS-R1   unknown
32  Total    Census Region 2: Midwest            CENS-R2   unknown
33  Total      Census Region 3: South            CENS-R3   unknown
34  Total       Census Region 4: West            CENS-R4   unknown
35  Total  Census Region 1: Northeast            CENS-R1   unknown
36  Total    Census Region 2: Midwest            CENS-R2   unknown
37  Total      Census Region 3: South            CENS-R3   unknown
38  Total       Census Region 4: West            CENS-R4   unknown
39  Total  Census Region 1: Northeast            CENS-R1   unknown
40  Total    Census Region 2: Midwest            CENS-R2   unknown
41  Total      Census Region 3: South            CENS-R3   unknown
42  Total       Census Region 4: West            CENS-R4   unknown

   Cause of death  Deaths    Births          Death Rate Eclampsia  \
0         unknown   143.0   14093.0               10.15   unknown
1         unknown   256.0   30595.0                8.37   unknown
2         unknown    71.0   10300.0                6.89   unknown
3         unknown    18.0    2029.0   8.87 (Unreliable)       Yes
4         unknown    46.0    3280.0               14.02       Yes
5         unknown    25.0    3151.0                7.93       Yes
6         unknown   129.0   50851.0                2.54   unknown
7         unknown   273.0   64914.0                4.21   unknown
8         unknown   462.0  105341.0                4.39   unknown
9         unknown   253.0   75345.0                3.36   unknown
10        unknown   228.0   50171.0                4.54   unknown
11        unknown   488.0   81230.0                6.01   unknown
12        unknown   924.0  141878.0                6.51   unknown
13        unknown   356.0   75141.0                4.74   unknown
14        unknown    16.0    1025.0  15.61 (Unreliable)   unknown
15        unknown    47.0    2740.0               17.15   unknown
16        unknown    74.0    5689.0               13.01   unknown
17        unknown    12.0    1494.0   8.03 (Unreliable)   unknown
18        unknown    18.0    1764.0  10.20 (Unreliable)   unknown
19        unknown    27.0    3100.0                8.71   unknown
20        unknown    52.0    4031.0               12.90   unknown
21        unknown    71.0    6309.0               11.25   unknown
22        unknown    21.0    2063.0               10.18   unknown
23        unknown    60.0    6580.0                9.12   unknown
24        unknown   103.0    9438.0               10.91   unknown
25        unknown   223.0   17906.0               12.45   unknown
26        unknown    86.0    8879.0                9.69   unknown
27        unknown   132.0   18064.0                7.31   unknown
28        unknown   267.0   24997.0               10.68   unknown
29        unknown   482.0   46520.0               10.36   unknown
30        unknown   162.0   17191.0                9.42   unknown
31        unknown   256.0   24231.0               10.56   unknown
32        unknown   501.0   37587.0               13.33   unknown
33        unknown   807.0   55358.0               14.58   unknown
34        unknown   263.0   25205.0               10.43   unknown
35        unknown    14.0    1053.0  13.30 (Unreliable)   unknown
36        unknown    20.0    1928.0               10.37   unknown
37        unknown    64.0    4898.0               13.07   unknown
38        unknown    33.0    2353.0               14.02   unknown
39        unknown   220.0   18684.0               11.77   unknown
40        unknown   540.0   45140.0               11.96   unknown
41        unknown   696.0   53564.0               12.99   unknown
42        unknown   171.0   16753.0               10.21   unknown

   Gestational Diabetes Gestational Hypertension Gonorrhea Hepatitis B  \
0               unknown                  unknown   unknown     unknown
1               unknown                  unknown   unknown     unknown
2               unknown                  unknown   unknown     unknown
3               unknown                  unknown   unknown     unknown
4               unknown                  unknown   unknown     unknown
5               unknown                  unknown   unknown     unknown
6                   Yes                  unknown   unknown     unknown
7                   Yes                  unknown   unknown     unknown
8                   Yes                  unknown   unknown     unknown
9                   Yes                  unknown   unknown     unknown
10              unknown                      Yes   unknown     unknown
11              unknown                      Yes   unknown     unknown
12              unknown                      Yes   unknown     unknown
13              unknown                      Yes   unknown     unknown
14              unknown                  unknown       Yes     unknown
15              unknown                  unknown       Yes     unknown
16              unknown                  unknown       Yes     unknown
17              unknown                  unknown       Yes     unknown
18              unknown                  unknown   unknown         Yes
19              unknown                  unknown   unknown     unknown
20              unknown                  unknown   unknown     unknown
21              unknown                  unknown   unknown     unknown
22              unknown                  unknown   unknown     unknown
23              unknown                  unknown   unknown     unknown
24              unknown                  unknown   unknown     unknown
25              unknown                  unknown   unknown     unknown
26              unknown                  unknown   unknown     unknown
27              unknown                  unknown   unknown     unknown
28              unknown                  unknown   unknown     unknown
29              unknown                  unknown   unknown     unknown
30              unknown                  unknown   unknown     unknown
31              unknown                  unknown   unknown     unknown
32              unknown                  unknown   unknown     unknown
33              unknown                  unknown   unknown     unknown
34              unknown                  unknown   unknown     unknown
35              unknown                  unknown   unknown     unknown
36              unknown                  unknown   unknown     unknown
37              unknown                  unknown   unknown     unknown
38              unknown                  unknown   unknown     unknown
39              unknown                  unknown   unknown     unknown
40              unknown                  unknown   unknown     unknown
41              unknown                  unknown   unknown     unknown
42              unknown                  unknown   unknown     unknown

   Hepatitis C Pre-pregnancy Diabetes Pre-pregnancy Hypertension  \
0      unknown                unknown                    unknown
1      unknown                unknown                    unknown
2      unknown                unknown                    unknown
3      unknown                unknown                    unknown
4      unknown                unknown                    unknown
5      unknown                unknown                    unknown
6      unknown                unknown                    unknown
7      unknown                unknown                    unknown
8      unknown                unknown                    unknown
9      unknown                unknown                    unknown
10     unknown                unknown                    unknown
11     unknown                unknown                    unknown
12     unknown                unknown                    unknown
13     unknown                unknown                    unknown
14     unknown                unknown                    unknown
15     unknown                unknown                    unknown
16     unknown                unknown                    unknown
17     unknown                unknown                    unknown
18     unknown                unknown                    unknown
19         Yes                unknown                    unknown
20         Yes                unknown                    unknown
21         Yes                unknown                    unknown
22         Yes                unknown                    unknown
23     unknown                    Yes                    unknown
24     unknown                    Yes                    unknown
25     unknown                    Yes                    unknown
26     unknown                    Yes                    unknown
27     unknown                unknown                        Yes
28     unknown                unknown                        Yes
29     unknown                unknown                        Yes
30     unknown                unknown                        Yes
31     unknown                unknown                    unknown
32     unknown                unknown                    unknown
33     unknown                unknown                    unknown
34     unknown                unknown                    unknown
35     unknown                unknown                    unknown
36     unknown                unknown                    unknown
37     unknown                unknown                    unknown
38     unknown                unknown                    unknown
39     unknown                unknown                    unknown
40     unknown                unknown                    unknown
41     unknown                unknown                    unknown
42     unknown                unknown                    unknown

   Previous Preterm Birth Syphilis Tobacco Use
0                 unknown  unknown     unknown
1                 unknown  unknown     unknown
2                 unknown  unknown     unknown
3                 unknown  unknown     unknown
4                 unknown  unknown     unknown
5                 unknown  unknown     unknown
6                 unknown  unknown     unknown
7                 unknown  unknown     unknown
8                 unknown  unknown     unknown
9                 unknown  unknown     unknown
10                unknown  unknown     unknown
11                unknown  unknown     unknown
12                unknown  unknown     unknown
13                unknown  unknown     unknown
14                unknown  unknown     unknown
15                unknown  unknown     unknown
16                unknown  unknown     unknown
17                unknown  unknown     unknown
18                unknown  unknown     unknown
19                unknown  unknown     unknown
20                unknown  unknown     unknown
21                unknown  unknown     unknown
22                unknown  unknown     unknown
23                unknown  unknown     unknown
24                unknown  unknown     unknown
25                unknown  unknown     unknown
26                unknown  unknown     unknown
27                unknown  unknown     unknown
28                unknown  unknown     unknown
29                unknown  unknown     unknown
30                unknown  unknown     unknown
31                    Yes  unknown     unknown
32                    Yes  unknown     unknown
33                    Yes  unknown     unknown
34                    Yes  unknown     unknown
35                unknown      Yes     unknown
36                unknown      Yes     unknown
37                unknown      Yes     unknown
38                unknown      Yes     unknown
39                unknown  unknown         Yes
40                unknown  unknown         Yes
41                unknown  unknown         Yes
42                unknown  unknown         Yes

In [166]:
# Save df_cleaned2 to a CSV file
df_total_cleaned.to_csv('df_total_cleaned.csv', index=False)